port: 5435
db-name: postgres
db-args: "sslmode=disable"
db-user: root
db-password: kyc
postgres-addr: localhost:5432
db-migration: true

clerk:
  api-token: sk_test_5devVMCSJ5qyLMItth6bNPL792gaoVOBZrzfjvInSF

supabase:
  api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dHJqcXNkaXF5YWd1cmV2Z292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUyODI4OTcsImV4cCI6MjAxMDg1ODg5N30.KgKYJC6CfGJXZOfS_eTa-GhZaBpxoygZy3Ld7ByQKtw"
  base-url: "https://lztrjqsdiqyagurevgov.supabase.co"

onebrick:
  base-url: https://sandbox.onebrick.io/v1
  client-id: db14faff-0686-4493-8d35-b249bf2c77d6
  client-secret: tMbKbZwIObdylGm6yYdTA9vLspR9w7
  redirect-url: "https://huge-daily-hog.ngrok-free.app/onebrick/callback"

creditcheck:
  base-url: https://api.creditchek.africa/v1
  public_key: "JCVJ2sQzscrc76v9v6GDXc237HO1EDycroZiyUfMW7qw+a3/DU16JoCdcky0S9Sm"

resend:
  api-key: "re_2c4oMT9c_2i3FMR8kcF5nGn4HeBvsmfmK"
  email-from: "Sinbad <kyc@sinbadhq.com>"

idenfy:
  base-url: https://ivs.idenfy.com
  api-key: voMXIZEjoX8
  api-secret: pdavE8xRAKfrBmhdxyfr


