env: PROD
port: 5435
db-name: postgres
db-args: "sslmode=disable"
db-user: postgres
db-password: 0EoXHl4rSOTNkOUs
postgres-addr: db.lztrjqsdiqyagurevgov.supabase.co:5432
db-migration: true

supabase:
  api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dHJqcXNkaXF5YWd1cmV2Z292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUyODI4OTcsImV4cCI6MjAxMDg1ODg5N30.KgKYJC6CfGJXZOfS_eTa-GhZaBpxoygZy3Ld7ByQKtw"
  base-url: "https://lztrjqsdiqyagurevgov.supabase.co"

onebrick:
  base-url: https://sandbox.onebrick.io/v1
  client-id: 5500802e-196c-4f32-92a0-d28ceaf99a19
  client-secret: BUChl8HXmNoqKq5B8ukvv0zu23ulvy
  redirect-url: "https://kyc-b6dd115716ab.herokuapp.com/onebrick/callback"